config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # トップページ
  root 'home#top'

  # ユーザー管理
  resources :users, only: %i[index show new create edit update]

  # セッション管理（ログイン・ログアウト）
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # 投稿管理
  resources :posts, only: %i[index new create edit update destroy show] do
    collection do
      get :my_posts
      get :liked_posts
      post :cancel
    end
    resources :likes, only: %i[create destroy]
  end

  # 映画情報管理
  resources :movies, only: %i[index show] do
    collection do
      post :save_selected
    end
  end

  # 音楽情報管理
  resources :musics, only: %i[index show] do
    collection do
      post :save_selected
    end
  end
end

app/models/music.rb
# frozen_string_literal: true

# 音楽モデル
class Music < ApplicationRecord
  has_many :posts

  def self.ransackable_attributes(_auth_object = nil)
    %w[id title artist spotify_track_id created_at updated_at]
  end
end

app/controllers/musics_controller.rb
# frozen_string_literal: true

class MusicsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def index
    @musics = if params[:query].present?
                search_musics(params[:query])
              else
                fetch_random_musics
              end

    @musics = Kaminari.paginate_array(@musics).page(params[:page]).per(9)
  end

  def save_selected
    selected_music_id = params[:selected_music_id]
    post_id = params[:post_id]

    if selected_music_id.present?
      begin
        @music = find_music(selected_music_id)
        save_music_to_session(@music)

        if post_id.present?
          handle_post_update(post_id, @music)
        else
          redirect_to new_post_path
        end
      end
    else
      redirect_to musics_path, alert: '音楽を選択してください。'
    end
  end

  private

  def search_musics(query)
    RSpotify::Track.search(query, limit: 20)
  end

  def fetch_random_musics
    random_query = generate_random_query
    begin
      tracks = RSpotify::Track.search(random_query, limit: 50)
      tracks.sample(10)
    end
  end

  def generate_random_query
    charset = [('a'..'z'), (0..9)].map(&:to_a).flatten
    Array.new(2) { charset.sample }.join
  end

  # 楽曲情報をSpotifyから取得
  def find_music(selected_music_id)
    RSpotify::Track.find(selected_music_id)
  end

  # セッションに楽曲情報を保存
  def save_music_to_session(music)
    session[:selected_music] = {
      id: music.id,
      name: music.name,
      artist: music.artists.map(&:name).join(', '),
      album: music.album.name,
      external_url: music.external_urls['spotify']
    }
  end

  # 投稿情報を更新
  def handle_post_update(post_id, music)
    post = Post.find(post_id)

    music_record = Music.find_or_create_by(spotify_track_id: music.id) do |m|
      m.spotify_track_id = music.id
      m.title = music.name
      m.artist = music.artists.map(&:name).join(', ')
    end

    post.music_id = music_record.id
    post.save

    redirect_to edit_post_path(post_id)
  end
end

app/helpers/musics_helper.rb
# frozen_string_literal: true

# 音楽情報のヘルパーモジュール
module MusicsHelper
end

app/views/musics/index.html.erb
<h1>楽曲一覧</h1>

<%= form_with url: musics_path, method: :get, local: true, class: 'search-form' do |form| %>
  <!-- 投稿IDを隠しフィールドとして渡す -->
  <%= hidden_field_tag :post_id, params[:post_id] %> 
  <%= form.text_field :query, placeholder: "キーワードを入力", value: params[:query], class: 'search-field' %>
  <%= form.submit '検索', class: "btn btn-primary search-button" %>
<% end %>

<%= form_with url: save_selected_musics_path, method: :post, local: true, class: "decision-form" do |form| %>
  <!-- 投稿IDを隠しフィールドとして渡す -->
  <%= hidden_field_tag :post_id, params[:post_id] %>   
  <div class="music-grid">
    <% if @musics.present? %>
      <% @musics.each do |music| %>
        <div class="music-item">
          <iframe src="https://open.spotify.com/embed/track/<%= music.id %>" width="100%" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
          <p class="music-title"><%= music.name %></p>
          <p class="music-artist"><%= music.artists.map(&:name).join(', ') %></p>
          <div class="radio-button-container">
            <label>
              <input type="radio" name="selected_music_id" value="<%= music.id %>"
                     <%= 'checked' if music.id.to_s == params[:selected_music_id] %>
                     data-title="<%= music.name %>"
                     data-artist="<%= music.artists.map(&:name).join(', ') %>">
            </label>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>楽曲が見つかりませんでした。</p>
    <% end %>
  </div>

  <div class="decision-button-container">
    <%= form.submit '決定', class: "btn btn-success decision-button" %>
  </div>

<% end %>

<!-- ページネーションリンク -->
<div class="pagination-container">
  <%= paginate @musics, theme: 'bootstrap-5' %>
</div>

<script>
  document.querySelectorAll('.music-item').forEach(item => {
    item.addEventListener('click', function() {
      const musicId = this.getAttribute('data-music-id');
      const radioButton = this.querySelector('input[type="radio"]');
      if (radioButton) {
        radioButton.checked = true;
      }
    });
  });
</script>